<a href="https://colab.research.google.com/github/Divakar201/ML-Projects/blob/master/CNN_using_tuner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install keras-tuner

     |████████████████████████████████| 61kB 3.2MB/s 
  Created wheel for keras-tuner: filename=keras_tuner-1.0.1-cp36-none-any.whl size=73200 sha256=2a180fe0a004eb376251c13c64ec860f1d61e0130bfb6d66678c62964c6be23d
  Stored in directory: /root/.cache/pip/wheels/b9/cc/62/52716b70dd90f3db12519233c3a93a5360bc672da1a10ded43
  Created wheel for terminaltables: filename=terminaltables-3.1.0-cp36-none-any.whl size=15356 sha256=34368df072b67c1f1304c25a7de462d9f66e37a5455db2c0b593e5c19673888f
  Stored in directory: /root/.cache/pip/wheels/30/6b/50/6c75775b681fb36cdfac7f19799888ef9d8813aff9e379663e
Successfully built keras-tuner terminaltables


In [0]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [3]:
print(tf.__version__)

1.15.0


In [0]:
fashion_mnist=keras.datasets.fashion_mnist

In [5]:
(X_train_img,y_train_labels),(X_test_img,y_test_labels)=fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [6]:
X_train_img.shape

(60000, 28, 28)

In [7]:
y_train_labels.shape

(60000,)

In [8]:
X_test_img.shape

(10000, 28, 28)

In [9]:
y_test_labels.shape

(10000,)

In [0]:
X_train_img=X_train_img/255.0

In [0]:
X_test_img=X_test_img/255.0

In [12]:
len(X_train_img)

60000

In [0]:
X_train_img=X_train_img.reshape(len(X_train_img),28,28,1)
X_test_img=X_test_img.reshape(len(X_test_img),28,28,1)

In [0]:
def build_model(hp):
  model=keras.Sequential([keras.layers.Conv2D(filters=hp.Int('conv_1_filter',min_value=32,max_value=128,step=16),
                                              kernel_size=hp.Choice('conv_1_kernel',values=[3,5]),
                                              activation='relu',
                                              input_shape=(28,28,1)),
                          keras.layers.Conv2D(filters=hp.Int('conv_2_filter',min_value=16,max_value=128,step=16),
                                              kernel_size=hp.Choice('conv_2_kernel',values=[3,5]),
                                              activation='relu'),
                          keras.layers.Flatten(),
                          keras.layers.Dense(units=hp.Int('dense_1_units',min_value=32,max_value=128,step=16),activation='relu'),
                          keras.layers.Dense(units=10,activation='softmax')])
  model.compile(optimizer=keras.optimizers.Adam(learning_rate=hp.Choice('learning_rate',values=[0.001,1e-3])),
                                                loss='sparse_categorical_crossentropy',metrics=['accuracy'])
  return model

In [0]:
from kerastuner import RandomSearch
from kerastuner.engine.hyperparameters import HyperParameters

In [0]:
#objective ['loss', 'acc', 'val_loss', 'val_acc']

In [17]:
randm_srch=RandomSearch(build_model,objective='val_acc',max_trials=5,directory='output',project_name='Mnist Fashion')

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [18]:
randm_srch.search(X_train_img,y_train_labels,epochs=3,validation_split=0.2,verbose=2)

Train on 48000 samples, validate on 12000 samples
Epoch 1/3
48000/48000 - 11s - loss: 0.4238 - acc: 0.8480 - val_loss: 0.3074 - val_acc: 0.8885
Epoch 2/3
48000/48000 - 5s - loss: 0.2813 - acc: 0.8979 - val_loss: 0.3032 - val_acc: 0.8875
Epoch 3/3
48000/48000 - 5s - loss: 0.2282 - acc: 0.9155 - val_loss: 0.2604 - val_acc: 0.9067


Train on 48000 samples, validate on 12000 samples
Epoch 1/3
48000/48000 - 6s - loss: 0.4182 - acc: 0.8491 - val_loss: 0.3073 - val_acc: 0.8867
Epoch 2/3
48000/48000 - 5s - loss: 0.2749 - acc: 0.8991 - val_loss: 0.2738 - val_acc: 0.9010
Epoch 3/3
48000/48000 - 5s - loss: 0.2207 - acc: 0.9188 - val_loss: 0.2728 - val_acc: 0.9042


Train on 48000 samples, validate on 12000 samples
Epoch 1/3
48000/48000 - 8s - loss: 0.3821 - acc: 0.8618 - val_loss: 0.2994 - val_acc: 0.8916
Epoch 2/3
48000/48000 - 8s - loss: 0.2415 - acc: 0.9105 - val_loss: 0.2715 - val_acc: 0.9038
Epoch 3/3
48000/48000 - 8s - loss: 0.1753 - acc: 0.9348 - val_loss: 0.2567 - val_acc: 0.9136


Train on 48000 samples, validate on 12000 samples
Epoch 1/3
48000/48000 - 6s - loss: 0.3862 - acc: 0.8610 - val_loss: 0.2933 - val_acc: 0.8941
Epoch 2/3
48000/48000 - 6s - loss: 0.2342 - acc: 0.9139 - val_loss: 0.2602 - val_acc: 0.9082
Epoch 3/3
48000/48000 - 6s - loss: 0.1671 - acc: 0.9380 - val_loss: 0.2609 - val_acc: 0.9107


Train on 48000 samples, validate on 12000 samples
Epoch 1/3
48000/48000 - 6s - loss: 0.4052 - acc: 0.8543 - val_loss: 0.3038 - val_acc: 0.8863
Epoch 2/3
48000/48000 - 6s - loss: 0.2588 - acc: 0.9047 - val_loss: 0.2864 - val_acc: 0.8950
Epoch 3/3
48000/48000 - 6s - loss: 0.2012 - acc: 0.9240 - val_loss: 0.2568 - val_acc: 0.9080


INFO:tensorflow:Oracle triggered exit


In [0]:
final_model=randm_srch.get_best_models(num_models=1)[0]

In [20]:
final_model.fit(X_train_img,y_train_labels,epochs=10,validation_split=0.2,initial_epoch=3,verbose=2)

Train on 48000 samples, validate on 12000 samples
Epoch 4/10
48000/48000 - 8s - loss: 0.1258 - acc: 0.9532 - val_loss: 0.2819 - val_acc: 0.9113
Epoch 5/10
48000/48000 - 8s - loss: 0.0814 - acc: 0.9697 - val_loss: 0.3166 - val_acc: 0.9092
Epoch 6/10
48000/48000 - 8s - loss: 0.0598 - acc: 0.9781 - val_loss: 0.3660 - val_acc: 0.9084
Epoch 7/10
48000/48000 - 8s - loss: 0.0355 - acc: 0.9870 - val_loss: 0.4529 - val_acc: 0.9129
Epoch 8/10
48000/48000 - 8s - loss: 0.0369 - acc: 0.9871 - val_loss: 0.4582 - val_acc: 0.9111
Epoch 9/10
48000/48000 - 8s - loss: 0.0265 - acc: 0.9908 - val_loss: 0.4756 - val_acc: 0.9133
Epoch 10/10
48000/48000 - 8s - loss: 0.0203 - acc: 0.9930 - val_loss: 0.5989 - val_acc: 0.9077


In [0]:
y_predict=final_model.predict_classes(X_test_img)

In [35]:
y_predict

array([9, 2, 1, ..., 8, 1, 5])

In [0]:
from sklearn.metrics import classification_report

In [38]:
print(classification_report(y_test_labels,y_predict))

              precision    recall  f1-score   support

           0       0.89      0.78      0.83      1000
           1       0.99      0.98      0.98      1000
           2       0.81      0.85      0.83      1000
           3       0.90      0.93      0.92      1000
           4       0.90      0.77      0.83      1000
           5       0.99      0.97      0.98      1000
           6       0.67      0.81      0.73      1000
           7       0.95      0.98      0.97      1000
           8       0.98      0.97      0.98      1000
           9       0.97      0.97      0.97      1000

    accuracy                           0.90     10000
   macro avg       0.91      0.90      0.90     10000
weighted avg       0.91      0.90      0.90     10000



In [0]:
final_model.save('mnist_fashion.h5')

In [0]:
from tensorflow.keras.models import load_model

In [0]:
fashion_model=load_model('mnist_fashion.h5')

In [62]:
fashion_model.predict_classes(X_test_img)

array([9, 2, 1, ..., 8, 1, 5])

In [69]:
X_test_img[0].shape

(28, 28, 1)

In [75]:
fashion_model.predict_classes(X_test_img[0].reshape((1,)+X_test_img[0].shape))

array([9])